name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ba63e325c4c304e6a29b027d04d4199bbb71cafde18f32be88c34cb205e4d0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
