name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9268197cb06e35c87b48197b8df8c129fb97f208fceb6da1231196432c67ab3b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
