name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d6cdea2a9d6286ab9703176474ad24c4642775bfcccded7655708099021a7c4"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
